name: Save-Player-Position
author: Omar Radwan
main: spigot.savePlayerPosition.project.Main
version: 1.1.0
api-version: 1.19

commands:
  spp:
    description: Root command for all spp commands
    usage: /spp <command>