name: Save-Player-Position
author: Omar Radwan
main: spigot.savePlayerPosition.project.Main
version: 0.0.5

commands:
  spp:
    description: Root command for all spp commands
    usage: /spp <command>